config/routes.rb
require 'sidekiq/web'
Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]

require 'admin_constraint'

Rails.application.routes.draw do

  root 'welcome#index'

  post 'supersignin', to: 'user_sessions#supersignin', as: :supersignin

  mount Sidekiq::Web, at: '/sidekiq', :constraints => AdminConstraint.new

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get 'signin', to: 'user_sessions#new'
  get 'signup', to: 'users#new'
  delete 'signout', to: 'user_sessions#destroy'

  resources :user_transactions, only: [:index, :new, :show]
  resources :user_sessions, only: [:create]
  resources :users, only: [:create, :update, :new, :edit]


  resource :password, only: [:edit, :update]

  resources :pages, only: [:show]

  resources :companies do
    resources :outcome_orders, shallow: true
    member do
      put :done
    end
    resources :company_documents do
      collection do
        delete :delete_by_name
      end
    end
  end

  resources :user_orders
  resources :user_transactions
  resources :user_goods
  resources :user_companies, only: [:index] do
    member do
      get :income
      get :outcome
    end
  end

  resources :banners, only: [:destroy]

  resources :orders
  resources :goods
  resources :password_resets, only: [:new, :create, :edit]

  get 'unsubscribe/:token', to: 'welcome#unsubscribe', as: :unsubscribe

  namespace :admin do
    root 'dashboard#index'
    resources :transactions
    resources :outcome_orders, only: [:index, :show] do
      member do
        patch :accept
        patch :reject
      end
    end
    resources :users
    resources :pages
    resources :banners
    resources :goods
    resources :orders do
      member do
        patch :complete
        patch :cancel
      end
    end
    resources :lockings
    resources :users
    resources :companies do
      member do
        patch :rework
        patch :start_review
        patch :accept
        patch :reject
      end
      resources :transactions, controller: 'company_transactions'
    end
  end

  get "error" => "errors#show", :as => "error"
  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  get '*anything', to: 'errors#show', code: 404
end

app/models/company.rb
class Company < ApplicationRecord
  FORMS = %w(LEGAL INDIVIDUAL PERSON)

  include PgSearch
  extend Enumerize
  include RegistrationSteps
  include CompanyModerationWorkflow

  # Не сохраняемый атрибут используется в форме для dadata suggestions
  #
  attr_accessor :party

  attribute :form, :string, default: 'LEGAL'

  scope :ordered, -> { order 'id desc' }
  pg_search_scope :search_by_name,
    against: { name: 'A', management_name: 'B', inn: 'B', ogrn: 'B', kpp: 'B', email: 'A', phone: 'A', management_post: 'C', address: 'D' },
    using: { tsearch: { negation: true, dictionary: 'russian', prefix: true } }

  scope :active, -> { with_accepted_state }

  belongs_to :user, counter_cache: true
  belongs_to :account, class_name: 'OpenbillAccount'
  belongs_to :moderator, class_name: 'User'

  has_many :goods
  has_many :documents, class_name: 'CompanyDocument'
  has_many :outcome_orders
  has_many :buyer_lockings, class_name: 'OpenbillLocking', inverse_of: :buyer, foreign_key: :buyer_id
  has_many :seller_lockings, class_name: 'OpenbillLocking', inverse_of: :seller, foreign_key: :seller_id
  has_many :requisites, through: :outcome_orders

  before_validation do
    self.phone = Phoner::Phone.parse(phone).to_s if phone.present?
  end

  validates :form, presence: true, inclusion: FORMS
  validates :name, presence: true

  validates :inn, presence: true, inn_format: { mild: true }, uniqueness: { scope: :user_id }
  validates :ogrn, presence: true, ogrn_format: true
  validates :kpp, presence: true, kpp_format: true, if: :legal?

  validates :email, presence: true, email: true
  validates :phone, presence: true, phone: true

  before_create :create_account

  enumerize :form,
    in: FORMS,
    predicates: true,
    scope: true,
    default: FORMS.first

  delegate :amount, to: :account

  def last_used_requisite
    requisites.order('id desc').first
  end

  def verified?
    accepted?
  end

  def document_types
    if legal?
      DocumentTypes::Legal
    elsif individual?
      DocumentTypes::Individual
    elsif person?
      DocumentTypes::Person
    end
  end

  def document_categories
    document_types.map(&:key)
  end

  def inn_kpp
    [inn, kpp].compact.join(' / ')
  end

  def locked_amount
    Money.new buyer_lockings.with_locked_state.sum(:amount_cents)
  end

  def all_documents_loaded?
    return false unless persisted?
    documents.group(:category).count.keys.sort == document_categories.sort
  end

  def legal?
    form == 'LEGAL'
  end

  def individual?
    form == 'INDIVIDUAL'
  end

  def to_s
    "#{name} (#{state_text})"
  end

  def update_goods
    update_goods_verification verified?
  end

  private

  def update_goods_verification(flag)
    goods.update_all is_company_verified: flag
    Good.counter_culture_fix_counts
  end

  def create_account
    self.account ||= OpenbillAccount.create! category: OpenbillCategory.companies
  end
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < Admin::ApplicationController
  respond_to :html

  def show
    @company = Company.find params[:id]
    respond_with @company
  end

  def index
    render locals: {
      q: q,
      companies: companies,
      search_form: search_form
    }
  end

  def income
    @company = Company.find params[:id]
    respond_with @company
  rescue ActiveRecord::RecordInvalid  => err
    flash[:danger] = err.message
    render 'show'
  end

  def rework
    @company = Company.find params[:id]
    @company.rework! current_user
    redirect_to admin_company_path @company
  rescue ActiveRecord::RecordInvalid  => err
    flash[:danger] = err.message
    render 'show'
  end

  def start_review
    @company = Company.find params[:id]
    @company.review! current_user
    redirect_to admin_company_path @company
  rescue ActiveRecord::RecordInvalid  => err
    flash[:danger] = err.message
    render 'show'
  end

  def reject
    @company = Company.find params[:id]
    @company.reject! current_user, params.require(:company)[:reject_message]
    redirect_to admin_company_path @company
  rescue ActiveRecord::RecordInvalid  => err
    flash[:danger] = err.message
    render 'show'
  end

  def accept
    @company = Company.find params[:id]
    @company.accept! current_user
    redirect_to admin_company_path @company
  rescue ActiveRecord::RecordInvalid  => err
    flash[:danger] = err.message
    render 'show'
  end

  private

  def company_params
    params.require(:company).permit!
  end

  protected

  def q
    Company.ransack params[:q]
  end

  def search_form
    @search_form ||= SearchForm.new params.fetch(:search_form, {}).permit(:q)
  end

  def companies
    scope = Company.includes(:user, :account)
    scope = scope.search_by_name search_form.q if search_form.q.present?
    scope = scope.ransack(params[:q]).result

    scope.page params[:page]
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :require_login, except: [:index, :show]

  def index
    @companies = Company.active.order(:id)
    respond_with @companies
  end

  def new
    @company = build_company
    render locals: { step: params[:step] || @company.registration_step }, layout: 'simple'
  end

  def create
    @company = current_user.companies.create permitted_params

    case @company.registration_step
    when RegistrationSteps::InfoStep
      render 'new', locals: { step: @company.registration_step }, layout: 'simple'
    when RegistrationSteps::DocumentsStep
      render 'new', layout: 'simple', locals: { step: @company.registration_step }
    when RegistrationSteps::ModerationStep
      render 'awaiting_review'
    else
      raise 'Неизвестный или невозможный шаг регистрации'
    end
  end

  def edit
    @company = Company.find params[:id]
    authorize @company

    render 'new', locals: { step: @company.registration_step }, layout: 'simple'
  end

  def show
    @company = Company.find params[:id]
    authorize @company
    respond_with @company
  end

  def done
    @company = Company.find params[:id]
    authorize @company, :edit?

    if @company.all_documents_loaded?
      @company.submit! current_user if @company.draft?
      render 'new', locals: { step: @company.registration_step }, flash: { success: 'Компания ожидает подтверждения модератором' }
    else
      flash.now[:danger] = 'Загрузите сканы регистрационных документов'
      render 'new', locals: { step: @company.registration_step }
    end
  end

  def update
    @company = Company.find params[:id]
    authorize @company
    @company.update permitted_params

    render 'edit', locals: { step: @company.registration_step }
  end

  private

  def permitted_params
    params[:company].permit(:email, :phone, :party, :name, :inn, :ogrn, :form, :kpp, :address, :management_post, :management_name)
  end

  def build_company
    current_user.companies.with_draft_state.new email: current_user.email, phone: current_user.phone
  end
end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
  def admin_company_link(company)
    link_to admin_company_path(company) do
      company_icon company, company.name
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
  COMPANY_STATES_CLASSES = {
    'draft' => 'badge-info',
    'awaiting_review' => 'badge-warning',
    'being_reviewed' => 'badge-warning',
    'accepted' => 'badge-success',
    'rejected' => 'badge-danger'
  }

  def company_fields(company)
    [:created_at, :name, :inn, :ogrn, :kpp, :form_text, :phone, :email, :address, :management_post, :management_name]
  end

  def company_link(company)
    link_to company_path(company), class: 'company-link' do
      company_icon company, company.name
    end
  end

  def company_popover_content(company)
    if company.verified?
      "Организация прошла верификацию #{l company.accepted_at, format: :short}"
    else
      "Организация верификацию еще не прошла"
    end
  rescue
    binding.pry
  end

  def company_icon(company, text=nil)
    if company.verified?
      content_tag :span, data: { toggle: :tooltip }, title: company_popover_content(company) do
        fa_icon :trophy, text: text
      end
    else
      content_tag :span, data: { toggle: :tooltip }, title: company_popover_content(company) do
        fa_icon :briefcase, text: text
      end
    end
  end

  def company_management(company)
    if company.management_name.present?
      "#{company.management_name} (#{company.management_post})"
    end
  end

  def company_all_documents_loaded_tag(company)
    if company.all_documents_loaded?
      content_tag :span, 'Документы загружены', class: 'badge badge-success'
    else
      content_tag :span, 'Документы отсутсвуют', class: 'badge badge-default'
    end
  end

  def company_state_tag(company)
    content_tag :span, company.state_text, class: "badge #{COMPANY_STATES_CLASSES[company.workflow_state]}"
  end

  def company_reg_info(company)
    content_tag :span, "#{company.inn} / #{company.ogrn}"
  end

  def company_form_collection
    [
      ['Юридическое лицо', 'LEGAL'],
      ['Индивидуальный предприниматель', 'INDIVIDUAL']
    ]
  end

  def humanized_form(form)
    I18n.t form, scope: [:helpers, :company_forms]
  end

  def new_company_step_one_title(company)
    title = '1. Сведения об организации'

    if company.persisted?
      title << " (указаны) #{check_circle true}"
    end

    title.html_safe
  end

  def new_company_step_two_title(company)
    title = "2. Загрузка уставных документов"

    if company.all_documents_loaded?
      title << " (загружены) #{check_circle true}"
    end

    title.html_safe
  end
end

app/views/admin/companies/_document.slim
.card style="width: #{ImageUploader::PREVIEW_WIDTH}px"
  a.card-img-top href=document.file.url data-lightbox="image-1"
    = image_tag document.file.preview.url, class: 'img-fuild'
  .card-block
    .card-title
      = link_to document.original_filename, document.file.url, target: '_blank'
    .card-text
      = number_to_human_size document.file_size

app/views/admin/companies/_documents.slim
- @company.document_types.each_with_index do |doc|
  h4.mt-4.mb-3= doc.title
  - documents = @company.documents.with_category(doc.key)
  - if documents.any?
    = render partial: 'document', collection: @company.documents.with_category(doc.key)
  - else
    .alert.alert-warning Отсутсвуют

app/views/admin/companies/_form.html.slim
= form_for @company do |f|
  - if @company.errors.any?
    #error_explanation
      h2 = "#{pluralize(@company.errors.count, "error")} prohibited this company from being saved:"
      ul
        - @company.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/admin/companies/_list.slim
table.table.table-condensed.table-striped
  thead
    tr
      th
        = sort_link q, :created_at, 'Дата регистрации'
      th 
        = sort_link q, :name, 'Полное наименоване'
      th Пользователь
      th Баланс
      th 
        = sort_link q, :goods, 'Предложений'
      th 
        = sort_link q, :state, 'Статус'
      th Действия

  tbody
    - companies.each do |company|
      tr
        td
          .text-nowrap
            = I18n.l company.created_at, format: :short
        td
          = link_to company.name, admin_company_path(company)
          |  
          br
          small.text-muted= company_reg_info company
          br
          small.text-muted
            = company_management company
        td
          = company.user.name || 'Имя не известно'
        td
          = humanized_money_with_symbol company.amount
        td
          = company_goods_count company
        td
          = company_state_tag company
          - unless company.draft?
            = company_all_documents_loaded_tag company
        td
          = link_to 'Подробнее', admin_company_path(company), class: 'btn btn-sm btn-outline-success'

app/views/admin/companies/_moderation.slim
.card
  h3.card-header 
    | Модерация 
    = company_state_tag company
    br
    small.text-muted
      | с 
      = l company.workflow_state_changed_at, format: :short

  .card-block
    - if company.accepted?
      .alert.alert-success
        | Организация принята #{company.moderator}
      = link_to 'Отправить на перепроверку', start_review_admin_company_path(company), method: :patch, class: 'btn btn-warning'

    - elsif company.rejected?
      .alert.alert-danger
        h4.alert-heading
          | Организация не проша проверку (модератор #{company.moderator})

        p= company.reject_message

      = link_to 'Отправить на перепроверку', start_review_admin_company_path(company), method: :patch, class: 'btn btn-warning'
    - elsif company.draft?
      .alert.alert-info Документы еще не загружены

    - elsif company.awaiting_review?
      .alert.alert-info 
        | Ожидает проверки с #{l company.awaiting_review_at || company.updated_at, format: :short} 
        = link_to 'Начать проверку', start_review_admin_company_path(company), method: :patch, class: 'btn btn-warning'

    - elsif company.being_reviewed?
      .alert.alert-info На проверке с #{l company.being_reviewed_at , format: :short}

      = link_to 'Прошла проверку', accept_admin_company_path(company), method: :patch, class: 'btn btn-success'

      hr
      = simple_form_for [:admin, company], url: reject_admin_company_path do |f|
        = f.input :reject_message, required: true
        = f.submit 'Проверку не прошла', class: 'btn btn-danger'
    - else
      .alert.alert-danger 
        strong Неизвестное состояние организации #{company.workflow_state}

app/views/admin/companies/_search_form.slim
= simple_form_for search_form, url: admin_companies_path, method: :get do |f|
  .row
    .col-md-9
      = f.input :q, placeholder: 'Наименование компании или ИНН', label: false, hint: false, as: :search, input_html: { class: 'mr-3' }, required: false
    .col-md-3
      = f.button :submit, class: 'btn btn-primary', data: { disabled_with: 'Отправляем..' }
      - if search_form.q.present?
        = link_to 'Сбросить поиск', admin_companies_path, class: 'btn btn-success-outline'

app/views/admin/companies/_tabs.slim
ul.nav.nav-tabs
  li.nav-item
    = link_to title_with_count('Все', Company.count), 
      admin_companies_path(q_to_param(workflow_state_eq: nil)), 
      class: active_class('nav-link', q_param(:workflow_state_eq).blank?)
  - %w(awaiting_review being_reviewed accepted rejected draft).each do |state|
    li.nav-item
      = link_to title_with_count(I18n.t(state, scope: [:enumerize, :defaults, :state]), Company.where(workflow_state: state).count), 
        admin_companies_path(q_to_param(workflow_state_eq: state)), 
        class: active_class('nav-link', q_param(:workflow_state_eq) == state)

app/views/admin/companies/edit.html.slim
h1 Editing company

== render 'form'

= link_to 'Show', @company
'|
= link_to 'Back', companies_path

app/views/admin/companies/index.html.slim
h1.mb-4 Организации (#{companies.total_count} из #{Company.count})
= render 'search_form', search_form: search_form

- unless search_form.q.present?
  .mb-4
    = render 'tabs', q: q

- if companies.empty?
  .lead По запросу ничего не найдено.
- else
  .pull-right= paginate companies
  = render 'list', companies: companies, q: q
  .pull-right= paginate companies

app/views/admin/companies/new.html.slim
h1 New company

== render 'form'

= link_to 'Back', companies_path

app/views/admin/companies/show.html.slim
= admin_companies_breadcrumbs @company
.row
  .col-md-6
    .mb-4
      - if @company.documents.exists?
        = render 'documents', documents: @company.documents
      - else
        p.lead Документы не загружены
    = render 'admin/companies/moderation', company: @company
  .col-md-6
    .card.mb-4
      h2.card-header Товары
      .card-block
        p Всего: #{link_to t(:goods_count, scope: :helpers, count: @company.goods.count), admin_goods_path(q: { company_id_eq: @company.id})}
        p Опубликовано: #{ link_to t(:goods_count, scope: :helpers, count: @company.goods.published.count), admin_goods_path(q: {company_id_eq: @company.id, workflow_state_eq: :published})}
    .card.mb-4
      h3.card-header Баланс
      .card-block
        h4.card-title На счету #{humanized_money_with_symbol @company.account.amount}
        h4.card-title Заблокировано #{humanized_money_with_symbol @company.locked_amount}

        .mt-4
          = link_to 'Пополнить', new_admin_company_transaction_path(@company, admin_transaction_form: { type: :income }), class: 'btn btn-success mr-4'
          = link_to 'Списать', new_admin_company_transaction_path(@company, admin_transaction_form: { type: :outcome }), class: 'btn btn-danger mr-4'
          = link_to 'История операций', admin_company_transactions_path(@company), class: 'card-link'

    .card.mb-4
      h3.card-header Данные компании
      .card-block
        p.card-text
          = render 'companies/details', company: @company
    .card
      h3.card-header 
        | Пользователь
        .pull-right
          = login_as_link @company.user
      .card-block
        p.card-text
          dl
            - [:created_at, :name, :email, :phone].each do |k|
              = show_field @company.user, k
= javascript_include_tag 'lightbox', 'data-turbolinks-track' => 'reload'