config/routes.rb
require 'sidekiq/web'
Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]

require 'admin_constraint'

Rails.application.routes.draw do

  root 'welcome#index'

  post 'supersignin', to: 'user_sessions#supersignin', as: :supersignin

  mount Sidekiq::Web, at: '/sidekiq', :constraints => AdminConstraint.new

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get 'signin', to: 'user_sessions#new'
  get 'signup', to: 'users#new'
  delete 'signout', to: 'user_sessions#destroy'

  resources :user_transactions, only: [:index, :new, :show]
  resources :user_sessions, only: [:create]
  resources :users, only: [:create, :update, :new, :edit]


  resource :password, only: [:edit, :update]

  resources :pages, only: [:show]

  resources :companies do
    resources :outcome_orders, shallow: true
    member do
      put :done
    end
    resources :company_documents do
      collection do
        delete :delete_by_name
      end
    end
  end

  resources :user_orders
  resources :user_transactions
  resources :user_goods
  resources :user_companies, only: [:index] do
    member do
      get :income
      get :outcome
    end
  end

  resources :banners, only: [:destroy]

  resources :orders
  resources :goods
  resources :password_resets, only: [:new, :create, :edit]

  get 'unsubscribe/:token', to: 'welcome#unsubscribe', as: :unsubscribe

  namespace :admin do
    root 'dashboard#index'
    resources :transactions
    resources :outcome_orders, only: [:index, :show] do
      member do
        patch :accept
        patch :reject
      end
    end
    resources :users
    resources :pages
    resources :banners
    resources :goods
    resources :orders do
      member do
        patch :complete
        patch :cancel
      end
    end
    resources :lockings
    resources :users
    resources :companies do
      member do
        patch :rework
        patch :start_review
        patch :accept
        patch :reject
      end
      resources :transactions, controller: 'company_transactions'
    end
  end

  get "error" => "errors#show", :as => "error"
  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  get '*anything', to: 'errors#show', code: 404
end

app/views/layouts/admin/_topmenu.slim
nav.navbar.navbar-toggleable-md.navbar-inverse.bg-danger.fixed-top
  .container
    = link_to admin_root_url, class: 'navbar-brand' do
      = fa_icon :bank, text: 'Админка'
    ul.navbar-nav.mr-auto.mt-2.mt-md-0
      -#= navbar_link_to 'Сайт', root_path, active: false
      -# = navbar_link_to 'Товары и услуги', root_path, count: Good.count
      = navbar_link_to 'Организации', admin_companies_path, count: Company.count
      = navbar_link_to 'Пользователи', admin_users_path, count: User.count
      = navbar_link_to 'Заказы', admin_orders_path, count: Order.count
      = navbar_link_to 'Заявки на вывод', admin_outcome_orders_path, count: OutcomeOrder.drafts.count
      = navbar_link_to 'Транзакциии', admin_transactions_path, count: OpenbillTransaction.count
      = navbar_link_to 'Уведомления', admin_banners_path, count: Banner.active.count
      = navbar_link_to 'Страницы', admin_pages_path, count: Page.active.count
    
    - if current_user.present?
      = render 'user_dropdown'

app/views/layouts/admin/application.slim
doctype html
html
  head
    title= application_title
    = stylesheet_link_tag 'admin/application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'admin/application', 'data-turbolinks-track' => 'reload'
    = render 'layouts/dadata'
    = csrf_meta_tags
  body
    = render 'layouts/admin/topmenu'
    main#content.container
      = render 'layouts/messages'
      = yield
    = render 'test_users' if can_supersignin?