config/routes.rb
require 'sidekiq/web'
Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]

require 'admin_constraint'

Rails.application.routes.draw do

  root 'welcome#index'

  post 'supersignin', to: 'user_sessions#supersignin', as: :supersignin

  mount Sidekiq::Web, at: '/sidekiq', :constraints => AdminConstraint.new

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get 'signin', to: 'user_sessions#new'
  get 'signup', to: 'users#new'
  delete 'signout', to: 'user_sessions#destroy'

  resources :user_transactions, only: [:index, :new, :show]
  resources :user_sessions, only: [:create]
  resources :users, only: [:create, :update, :new, :edit]


  resource :password, only: [:edit, :update]

  resources :pages, only: [:show]

  resources :companies do
    resources :outcome_orders, shallow: true
    member do
      put :done
    end
    resources :company_documents do
      collection do
        delete :delete_by_name
      end
    end
  end

  resources :user_orders
  resources :user_transactions
  resources :user_goods
  resources :user_companies, only: [:index] do
    member do
      get :income
      get :outcome
    end
  end

  resources :banners, only: [:destroy]

  resources :orders
  resources :goods
  resources :password_resets, only: [:new, :create, :edit]

  get 'unsubscribe/:token', to: 'welcome#unsubscribe', as: :unsubscribe

  namespace :admin do
    root 'dashboard#index'
    resources :transactions
    resources :outcome_orders, only: [:index, :show] do
      member do
        patch :accept
        patch :reject
      end
    end
    resources :users
    resources :pages
    resources :banners
    resources :goods
    resources :orders do
      member do
        patch :complete
        patch :cancel
      end
    end
    resources :lockings
    resources :users
    resources :companies do
      member do
        patch :rework
        patch :start_review
        patch :accept
        patch :reject
      end
      resources :transactions, controller: 'company_transactions'
    end
  end

  get "error" => "errors#show", :as => "error"
  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  get '*anything', to: 'errors#show', code: 404
end

app/models/company.rb
class Company < ApplicationRecord
  FORMS = %w(LEGAL INDIVIDUAL PERSON)

  include PgSearch
  extend Enumerize
  include RegistrationSteps
  include CompanyModerationWorkflow

  # Не сохраняемый атрибут используется в форме для dadata suggestions
  #
  attr_accessor :party

  attribute :form, :string, default: 'LEGAL'

  scope :ordered, -> { order 'id desc' }
  pg_search_scope :search_by_name,
    against: { name: 'A', management_name: 'B', inn: 'B', ogrn: 'B', kpp: 'B', email: 'A', phone: 'A', management_post: 'C', address: 'D' },
    using: { tsearch: { negation: true, dictionary: 'russian', prefix: true } }

  scope :active, -> { with_accepted_state }

  belongs_to :user, counter_cache: true
  belongs_to :account, class_name: 'OpenbillAccount'
  belongs_to :moderator, class_name: 'User'

  has_many :goods
  has_many :documents, class_name: 'CompanyDocument'
  has_many :outcome_orders
  has_many :buyer_lockings, class_name: 'OpenbillLocking', inverse_of: :buyer, foreign_key: :buyer_id
  has_many :seller_lockings, class_name: 'OpenbillLocking', inverse_of: :seller, foreign_key: :seller_id
  has_many :requisites, through: :outcome_orders

  before_validation do
    self.phone = Phoner::Phone.parse(phone).to_s if phone.present?
  end

  validates :form, presence: true, inclusion: FORMS
  validates :name, presence: true

  validates :inn, presence: true, inn_format: { mild: true }, uniqueness: { scope: :user_id }
  validates :ogrn, presence: true, ogrn_format: true
  validates :kpp, presence: true, kpp_format: true, if: :legal?

  validates :email, presence: true, email: true
  validates :phone, presence: true, phone: true

  before_create :create_account

  enumerize :form,
    in: FORMS,
    predicates: true,
    scope: true,
    default: FORMS.first

  delegate :amount, to: :account

  def last_used_requisite
    requisites.order('id desc').first
  end

  def verified?
    accepted?
  end

  def document_types
    if legal?
      DocumentTypes::Legal
    elsif individual?
      DocumentTypes::Individual
    elsif person?
      DocumentTypes::Person
    end
  end

  def document_categories
    document_types.map(&:key)
  end

  def inn_kpp
    [inn, kpp].compact.join(' / ')
  end

  def locked_amount
    Money.new buyer_lockings.with_locked_state.sum(:amount_cents)
  end

  def all_documents_loaded?
    return false unless persisted?
    documents.group(:category).count.keys.sort == document_categories.sort
  end

  def legal?
    form == 'LEGAL'
  end

  def individual?
    form == 'INDIVIDUAL'
  end

  def to_s
    "#{name} (#{state_text})"
  end

  def update_goods
    update_goods_verification verified?
  end

  private

  def update_goods_verification(flag)
    goods.update_all is_company_verified: flag
    Good.counter_culture_fix_counts
  end

  def create_account
    self.account ||= OpenbillAccount.create! category: OpenbillCategory.companies
  end
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < Admin::ApplicationController
  respond_to :html

  def show
    @company = Company.find params[:id]
    respond_with @company
  end

  def index
    render locals: {
      q: q,
      companies: companies,
      search_form: search_form
    }
  end

  def income
    @company = Company.find params[:id]
    respond_with @company
  rescue ActiveRecord::RecordInvalid  => err
    flash[:danger] = err.message
    render 'show'
  end

  def rework
    @company = Company.find params[:id]
    @company.rework! current_user
    redirect_to admin_company_path @company
  rescue ActiveRecord::RecordInvalid  => err
    flash[:danger] = err.message
    render 'show'
  end

  def start_review
    @company = Company.find params[:id]
    @company.review! current_user
    redirect_to admin_company_path @company
  rescue ActiveRecord::RecordInvalid  => err
    flash[:danger] = err.message
    render 'show'
  end

  def reject
    @company = Company.find params[:id]
    @company.reject! current_user, params.require(:company)[:reject_message]
    redirect_to admin_company_path @company
  rescue ActiveRecord::RecordInvalid  => err
    flash[:danger] = err.message
    render 'show'
  end

  def accept
    @company = Company.find params[:id]
    @company.accept! current_user
    redirect_to admin_company_path @company
  rescue ActiveRecord::RecordInvalid  => err
    flash[:danger] = err.message
    render 'show'
  end

  private

  def company_params
    params.require(:company).permit!
  end

  protected

  def q
    Company.ransack params[:q]
  end

  def search_form
    @search_form ||= SearchForm.new params.fetch(:search_form, {}).permit(:q)
  end

  def companies
    scope = Company.includes(:user, :account)
    scope = scope.search_by_name search_form.q if search_form.q.present?
    scope = scope.ransack(params[:q]).result

    scope.page params[:page]
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :require_login, except: [:index, :show]

  def index
    @companies = Company.active.order(:id)
    respond_with @companies
  end

  def new
    @company = build_company
    render locals: { step: params[:step] || @company.registration_step }, layout: 'simple'
  end

  def create
    @company = current_user.companies.create permitted_params

    case @company.registration_step
    when RegistrationSteps::InfoStep
      render 'new', locals: { step: @company.registration_step }, layout: 'simple'
    when RegistrationSteps::DocumentsStep
      render 'new', layout: 'simple', locals: { step: @company.registration_step }
    when RegistrationSteps::ModerationStep
      render 'awaiting_review'
    else
      raise 'Неизвестный или невозможный шаг регистрации'
    end
  end

  def edit
    @company = Company.find params[:id]
    authorize @company

    render 'new', locals: { step: @company.registration_step }, layout: 'simple'
  end

  def show
    @company = Company.find params[:id]
    authorize @company
    respond_with @company
  end

  def done
    @company = Company.find params[:id]
    authorize @company, :edit?

    if @company.all_documents_loaded?
      @company.submit! current_user if @company.draft?
      render 'new', locals: { step: @company.registration_step }, flash: { success: 'Компания ожидает подтверждения модератором' }
    else
      flash.now[:danger] = 'Загрузите сканы регистрационных документов'
      render 'new', locals: { step: @company.registration_step }
    end
  end

  def update
    @company = Company.find params[:id]
    authorize @company
    @company.update permitted_params

    render 'edit', locals: { step: @company.registration_step }
  end

  private

  def permitted_params
    params[:company].permit(:email, :phone, :party, :name, :inn, :ogrn, :form, :kpp, :address, :management_post, :management_name)
  end

  def build_company
    current_user.companies.with_draft_state.new email: current_user.email, phone: current_user.phone
  end
end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
  def admin_company_link(company)
    link_to admin_company_path(company) do
      company_icon company, company.name
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
  COMPANY_STATES_CLASSES = {
    'draft' => 'badge-info',
    'awaiting_review' => 'badge-warning',
    'being_reviewed' => 'badge-warning',
    'accepted' => 'badge-success',
    'rejected' => 'badge-danger'
  }

  def company_fields(company)
    [:created_at, :name, :inn, :ogrn, :kpp, :form_text, :phone, :email, :address, :management_post, :management_name]
  end

  def company_link(company)
    link_to company_path(company), class: 'company-link' do
      company_icon company, company.name
    end
  end

  def company_popover_content(company)
    if company.verified?
      "Организация прошла верификацию #{l company.accepted_at, format: :short}"
    else
      "Организация верификацию еще не прошла"
    end
  rescue
    binding.pry
  end

  def company_icon(company, text=nil)
    if company.verified?
      content_tag :span, data: { toggle: :tooltip }, title: company_popover_content(company) do
        fa_icon :trophy, text: text
      end
    else
      content_tag :span, data: { toggle: :tooltip }, title: company_popover_content(company) do
        fa_icon :briefcase, text: text
      end
    end
  end

  def company_management(company)
    if company.management_name.present?
      "#{company.management_name} (#{company.management_post})"
    end
  end

  def company_all_documents_loaded_tag(company)
    if company.all_documents_loaded?
      content_tag :span, 'Документы загружены', class: 'badge badge-success'
    else
      content_tag :span, 'Документы отсутсвуют', class: 'badge badge-default'
    end
  end

  def company_state_tag(company)
    content_tag :span, company.state_text, class: "badge #{COMPANY_STATES_CLASSES[company.workflow_state]}"
  end

  def company_reg_info(company)
    content_tag :span, "#{company.inn} / #{company.ogrn}"
  end

  def company_form_collection
    [
      ['Юридическое лицо', 'LEGAL'],
      ['Индивидуальный предприниматель', 'INDIVIDUAL']
    ]
  end

  def humanized_form(form)
    I18n.t form, scope: [:helpers, :company_forms]
  end

  def new_company_step_one_title(company)
    title = '1. Сведения об организации'

    if company.persisted?
      title << " (указаны) #{check_circle true}"
    end

    title.html_safe
  end

  def new_company_step_two_title(company)
    title = "2. Загрузка уставных документов"

    if company.all_documents_loaded?
      title << " (загружены) #{check_circle true}"
    end

    title.html_safe
  end
end

app/views/companies/_details.slim
dl
  - company_fields(company).each do |k|
    = show_field company, k

app/views/companies/_documents.slim
.row.mb-4
  - company.documents.each do |d|
    .col-md-3.media
      = link_to d.file.url, target: '_blank' do
        = image_tag d.file.thumb.url, style: 'width: 64px', class: 'd-flex mr-3'
      .media-body
        = d.file.file.extension
        div= number_to_human_size d.file.size

app/views/companies/_form.slim
#accordion role="tablist" aria-multiselectable="true"
  = render layout: 'collapse_card', 
    locals: { show: step==1, heading_id: 'headingOne', parent: 'accordion', content_id: 'collapseBase', title: new_company_step_one_title(company) } do
    = render 'companies/form_basic', company: company, disabled: company.persisted?

  = render layout: 'collapse_card', 
    locals: { show: step==2, heading_id: 'headingTwo', parent: 'accordion', content_id: 'collapseDocuments', title: new_company_step_two_title(company) } do
      - if company.persisted?
        = render 'companies/form_documents', company: company
      - else
        .lead Укажите сначала основные сведения об организации
        
  = render layout: 'collapse_card', 
    locals: { show: step==3, heading_id: 'heading3', parent: 'accordion', content_id: 'collapseWait', title: '3. Проверка документов' } do
    - if company.awaiting_review?
      .lead Данные находятся на проверке у менеджера
    - elsif company.draft?
      .lead Укажите основные сведения и загрузите документы
    - elsif company.rejected?
      .lead
        p 
          | Организация не прошла проверку. Причина: 
          = company.reject_message

app/views/companies/_form_basic.slim
= simple_form_for company do |f|
  = f.error_notification

  - unless disabled
    .mb-5
      = f.input :party, label: false, input_html: { data: { suggestion: 'party' } }

  .row
    .col-md-4
      = f.input :form, collection: company_form_collection, include_blank: false, label: false, input_html: { data: { suggestion: 'type' } }, disabled: disabled
    .col-md-8
      = f.input :name, label: false, input_html: { data: { suggestion: 'name' } }, disabled: disabled
  .row
    .col-md-4
      = f.input :inn, label: false, input_html: { data: { suggestion: 'inn' } }, disabled: disabled
    .col-md-4
      = f.input :ogrn, label: false, input_html: { data: { suggestion: 'ogrn' } }, disabled: disabled
    .col-md-4
      = f.input :kpp, label: false, input_html: { data: { suggestion: 'kpp' } }, disabled: disabled
  .row
    .col-md-12
      = f.input :address, label: false, input_html: { data: { suggestion: 'address' } }, disabled: disabled
  .row
    .col-md-6
      = f.input :management_post, label: false, input_html: { data: { suggestion: 'management-post' } }, disabled: disabled
    .col-md-6
      = f.input :management_name, label: false, input_html: { data: { suggestion: 'management-name' } }, disabled: disabled
  .row
    .col-md-6
      = f.input :phone, label: false, disabled: disabled
    .col-md-6
      = f.input :email, label: false, disabled: disabled


  - if disabled
    .mt-4
    .row
      .col-md-6
      .col-md-6
        .pull-right
          = link_to 'Изменить сведения', new_company_path(company.id, step: 1), class: 'btn btn-outline-primary btn-sm'
          p.text-muted.mt-2
            small Идентификатор компании ##{company.id}
    .cleargix
  - else
    .mt-4
      = f.button :submit, value: 'Продолжить', class: 'btn btn-primary'

app/views/companies/_form_documents.slim
- company.document_types.each_with_index do |doc|
  .row
    .col-md-4
      h4= doc.title
      p.m-t-md= doc.details if doc.details.present?

    .col-md-8
      = simple_form_for [company, CompanyDocument.new], multiple: true, html: { class: 'dropzone', data: { dropzone: true, company_id: company.id }} do |f|
        = hidden_field_tag :category, doc.key
        .fallback= file_field_tag 'file', multiple: true

        .dz-message data-ds-message=true
          .dz-message-header Перетащите файлы сюда
          .dz-message-details 
            | Принимаются разрешения: 
            strong= DocumentUploader::EXTENSION_WHITE_LIST.join(', ')
            .mt-2
              | Максимальный допустимый размер файла: 
              strong= number_to_human_size DocumentUploader::MAX_FILE_SIZE
        = render partial: 'dz_preview', collection: company.documents.with_category(doc.key)

  .clearfix
  hr


= render 'layouts/messages'

.mt-4
  = link_to 'Отправить на проверку', done_company_path(company), method: :put, class: 'btn btn-lg btn-primary', data: { review_button: true }

app/views/companies/_short.slim
h4= company

= render 'companies/details', company: company

small= link_to 'Страница компании', company_path(company), target: '_blank'

app/views/companies/edit.slim
h2.mb-1 Компания #{@company}
hr.mb-4

= render 'form', company: @company, step: step

app/views/companies/index.html.slim
.pull-right
  - if logged_in?
    = link_to 'Добавить свою', new_company_path, class: 'btn btn-outline-success'
  - else
    = link_to 'Добавить свою', new_user_path, class: 'btn btn-outline-success'

h1 Органиации (#{Company.active.count})

table.table.table-condensed.table-striped
  thead
    tr
      th Наименование
      th Адрес
      th Торговые предложения
  - @companies.each do |c|
    tr
      td
        .text-nowrap= company_link c
        .mt-2.text-muted
          small= company_reg_info c
      td.text-muted= c.address
      td.text-nowrap
        .pull-right= link_to t('helpers.goods_count', count: c.goods_count), company_path(c.id)

app/views/companies/new.slim
.pull-right.mt-2
  = link_to 'Управление организацими', user_companies_path, class: 'btn btn-sm btn-outline-primary'

h1.mb-4 Регистрация организации

- if @company.rejected?
  .mb-2.alert.alert-danger
    p Организация не прошла проверку: 
    = @company.reject_message

= render 'companies/form', company: @company, step: step

app/views/companies/show.slim
.row.mb-4
  .col-md-9
    .pull-right
      = company_state_tag @company
    h1.mb-2= @company
    span.mr-3= company_icon @company
    = @company.address


  .col-md-3
    - if logged_in?
      - if current_user.companies.include? @company
        .pull-right
          p Это моя компания
          .mb-2= link_to 'Редактировать реквизиты', edit_company_path(@company), class: 'btn btn-sm btn-outline-secondary'
          = link_to 'Другие предложения', user_goods_path(company_id: @company.id), class: 'btn btn-sm btn-outline-secondary'

hr

h2 Торговые предложения

= render 'goods/list', goods: @company.goods.available.view_order