config/routes.rb
require 'sidekiq/web'
Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]

require 'admin_constraint'

Rails.application.routes.draw do

  root 'welcome#index'

  post 'supersignin', to: 'user_sessions#supersignin', as: :supersignin

  mount Sidekiq::Web, at: '/sidekiq', :constraints => AdminConstraint.new

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get 'signin', to: 'user_sessions#new'
  get 'signup', to: 'users#new'
  delete 'signout', to: 'user_sessions#destroy'

  resources :user_transactions, only: [:index, :new, :show]
  resources :user_sessions, only: [:create]
  resources :users, only: [:create, :update, :new, :edit]


  resource :password, only: [:edit, :update]

  resources :pages, only: [:show]

  resources :companies do
    resources :outcome_orders, shallow: true
    member do
      put :done
    end
    resources :company_documents do
      collection do
        delete :delete_by_name
      end
    end
  end

  resources :user_orders
  resources :user_transactions
  resources :user_goods
  resources :user_companies, only: [:index] do
    member do
      get :income
      get :outcome
    end
  end

  resources :banners, only: [:destroy]

  resources :orders
  resources :goods
  resources :password_resets, only: [:new, :create, :edit]

  get 'unsubscribe/:token', to: 'welcome#unsubscribe', as: :unsubscribe

  namespace :admin do
    root 'dashboard#index'
    resources :transactions
    resources :outcome_orders, only: [:index, :show] do
      member do
        patch :accept
        patch :reject
      end
    end
    resources :users
    resources :pages
    resources :banners
    resources :goods
    resources :orders do
      member do
        patch :complete
        patch :cancel
      end
    end
    resources :lockings
    resources :users
    resources :companies do
      member do
        patch :rework
        patch :start_review
        patch :accept
        patch :reject
      end
      resources :transactions, controller: 'company_transactions'
    end
  end

  get "error" => "errors#show", :as => "error"
  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  get '*anything', to: 'errors#show', code: 404
end

app/controllers/admin/lockings_controller.rb
class Admin::LockingsController < Admin::ApplicationController
  def index
    @lockings = OpenbillLocking.order(:id)
    respond_with @lockings
  end
end

app/helpers/lockings_helper.rb
module LockingsHelper
  def locking_workflow_state_text(state)
    t(state, scope: [:enumerize, :locking_workflow_states])
  end
end

app/views/admin/lockings/_short.slim
.alert.alert-danger
  = locking_workflow_state_text order.locking.workflow_state
  - if order.locked?
    | : 
    strong= humanized_money_with_symbol order.locking.amount

- if order.locked?
  = link_to 'Заврешить покупку (отдать средства продавцу)', complete_admin_order_path(order), class: 'btn btn-success btn-sm', method: :patch
  = link_to 'Отклонить покупку (вернуть средства покупателю)', cancel_admin_order_path(order), class: 'btn btn-warning btn-sm', method: :patch

app/views/admin/lockings/index.html.slim
h1.mb-4 Блокировки
hr

table.table.table-condensed.table-striped
  thead
    tr
      th Дата
      th Покупатель
      th Продавец
      th Товар
      th Сумма
      th Состояние
      th Действия
  tbody
    - @lockings.each do |t|
      tr
        td
          .text-nowrap= l t.created_at, format: :short
        td= link_to t.buyer, admin_company_path(t.buyer)
        td= link_to t.seller, admin_company_path(t.seller)   
        td= link_to t.good, good_path(t.good)
        td.text-nowrap= humanized_money_with_symbol t.amount
        td
          .badge.badge-info= locking_workflow_state_text t.workflow_state     
        td 
          /- if t.locked?
            /= link_to 'Заврешить покупку (отдать средства продавцу)', accept_admin_locking_path(t), class: 'btn btn-success btn-sm', method: :patch
            /= link_to 'Отклонить покупку (вернуть средства покупателю)', reject_admin_locking_path(t), class: 'btn btn-warning btn-sm', method: :patch